language: node_js
dist: trusty
sudo: required
node_js:
- 9.5.0
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
addons:
  chrome: stable
before_deploy:
- npm run build
deploy:
  provider: npm
  email: harunurhan17@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: harunurhan/math-interval
    branch: master
